package api

import "math/rand"

// The window the amneziawg-linux-kernel-module README recommends for S1 and
// S2, which the generator uses for all four paddings, and what a generated
// padding has to leave room for: S4 rides on every transport packet, so the
// biggest one still has to fit the path the tunnel runs over - tunnel MTU +
// MessageTransportSize (32) + IPv4/UDP headers (28) + S4 <= 1500. Overshooting
// fragments every full-size packet, which is both slow and exactly the
// signature AmneziaWG is trying not to have.
const (
	MinRecommendedPadding = 15
	MaxRecommendedPadding = 150
	AssumedPathMTU        = 1500
	TransportPacketBytes  = 60
)

// GenerateObfuscation rolls a full AmneziaWG 3.1 parameter set that passes
// Validate at the given MTU.
//
// The shape follows what the AmneziaWG docs recommend for the mode this app
// always runs in - header protection on, RandomTrailers on - rather than
// randomising everything that could be randomised: the standard message types
// for H1-H4, because header protection encrypts the type field itself and
// custom headers add nothing an observer can see, and the recommended 8/80
// junk packet sizes. Jc is the one number left to chance, which is where the
// docs put it.
//
// MTU and HeaderProtectionKey are left alone: the caller knows the first, and
// the key has to come from a cryptographic source rather than from here.
func GenerateObfuscation(mtu int, distinctPaddings bool) *ObfuscationParams {
	s1, s2, s3, s4 := RecommendedPaddings(mtu, distinctPaddings)

	return &ObfuscationParams{
		Jc:             randomBetween(4, 12),
		Jmin:           8,
		Jmax:           80,
		S1:             s1,
		S2:             s2,
		S3:             s3,
		S4:             s4,
		H1:             1,
		H2:             2,
		H3:             3,
		H4:             4,
		RandomTrailers: true,
		DisableCookies: true,
	}
}

// RecommendedPaddings rolls S1-S4, either as one value repeated or as four
// independent draws.
//
// One value is what the AmneziaWG docs recommend while RandomTrailers is on:
// packet sizes float, and equal paddings are what stops the receiver reading
// one message type as another. The cost is that the gaps between the four
// message types stay exactly WireGuard's own (148/92/64/32), and an observer
// who can find the smallest packet of each type recovers that structure. Four
// separate values hide the structure and give up the receiver's margin, which
// is why it is a deliberate choice rather than the default.
//
// Every draw fits the same three ceilings - the recommended 15-150 window,
// S1's MTU-148 limit (the tightest of the four), and the room a transport
// packet leaves under the path MTU - so any of them is legal in any of the
// four slots. Above a tunnel MTU of about 1425 the last ceiling leaves nothing
// and the window collapses onto its floor.
func RecommendedPaddings(mtu int, distinct bool) (s1, s2, s3, s4 int) {
	hi := min(MaxRecommendedPadding, mtu-148, AssumedPathMTU-TransportPacketBytes-mtu)
	roll := func() int { return randomBetween(MinRecommendedPadding, hi) }

	if !distinct {
		padding := roll()
		return padding, padding, padding, padding
	}

	s1, s3, s4 = roll(), roll(), roll()
	// A collapsed window leaves nothing to re-roll; Validate reports the
	// S1+56 collision on its own if it comes to that.
	for range 100 {
		s2 = roll()
		if s1+56 != s2 {
			break
		}
	}
	return s1, s2, s3, s4
}

// randomBetween returns a value in [lo, hi], collapsing to lo when an MTU too
// small for the range has squeezed the window shut - the MTU check reports
// that on its own, and this must not panic in the meantime.
//
// math/rand rather than crypto/rand on purpose: these are packet shapes, not
// secrets, and the one value that is a secret - the header protection key -
// is generated by the backend from a cryptographic source.
func randomBetween(lo, hi int) int {
	if hi <= lo {
		return lo
	}
	return rand.Intn(hi-lo+1) + lo //nolint:gosec
}
